#!/bin/zsh
# Writes Config/Signing.local.xcconfig so PhotoCuller is signed with your (free) Apple Development certificate.
# A stable signing identity keeps folder permissions and the app's data across rebuilds.
set -e
cd "$(dirname "$0")/.."
cert=$(security find-certificate -a -c "Apple Development" -p 2>/dev/null | openssl x509 -noout -subject 2>/dev/null | head -1)
if [[ -z "$cert" ]]; then
  echo "No 'Apple Development' certificate found."
  echo "Open Xcode ▸ Settings ▸ Accounts, add your Apple ID, select it ▸ Manage Certificates… ▸ + ▸ Apple Development."
  exit 1
fi
team=$(echo "$cert" | sed -nE 's/.*OU *= *([A-Z0-9]{10}).*/\1/p')
if [[ -z "$team" ]]; then echo "Could not read the team ID from: $cert"; exit 1; fi
cat > Config/Signing.local.xcconfig <<CFG
// Generated by scripts/setup-signing.sh — local only (git-ignored).
CODE_SIGN_STYLE = Automatic
CODE_SIGN_IDENTITY = Apple Development
DEVELOPMENT_TEAM = $team
CFG
echo "Signing with team $team. Regenerating the Xcode project…"
command -v xcodegen >/dev/null && xcodegen generate || echo "Install xcodegen (brew install xcodegen) or reopen the project."
